package android.wgunn.collegeschedulelite.Entity;

import static androidx.room.ForeignKey.CASCADE;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.time.LocalDateTime;
/**
 * The CourseAssessmentEntity entity models a row in the course_assessments table. The CourseAssessmentEntity
 * represents a one-to-many relationship with a CourseEntity.
 */
@Entity(
    tableName = "course_assessments",
    foreignKeys = @ForeignKey(
            entity = CourseEntity.class,
            parentColumns = "id",
            childColumns = "course_id",
            onDelete = CASCADE
    ),
    indices = {@Index(value = {"course_id"})}
)
public class CourseAssessmentEntity {

    /**
     * The autogenerated primary key
     */
    @PrimaryKey(autoGenerate = true)
    private Long id;

    /**
     * The parent course ID
     */
    @ColumnInfo(name = "course_id")
    private Long courseId;

    /**
     * The assessment title
     */
    @ColumnInfo(name = "title")
    private String title;

    /**
     * The assessment type (performance or objective)
     */
    @ColumnInfo(name = "type")
    private String type;

    /**
     * The assessment date / time
     */
    @ColumnInfo(name = "date")
    private LocalDateTime dateTime;

    /**
     * The course asessment ID getter
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * The course assessment ID setter
     * @param id The autogenerated ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * The parent course ID getter
     * @return courseId
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * The parent course ID setter
     * @param courseId The parent course ID
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * The assessment title getter
     * @return title
     */
    public String getTitle() {
        return title;
    }

    /**
     * The assessment title setter
     * @param title The course title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * The assessment type getter
     * @return type
     */
    public String getType() {
        return type;
    }

    /**
     * The assessment type setter
     * @param type The assessment type
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * The date / time getter
     * @return dateTime
     */
    public LocalDateTime getDateTime() {
        return dateTime;
    }

    /**
     * The date setter
     * @param dateTime The assessment date
     */
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }
}
