package android.wgunn.collegeschedulelite.Entity;

import static androidx.room.ForeignKey.CASCADE;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * The CourseNote entity models a row in the course_notes table. The CourseNote
 * represents a one-to-many relationship with a Course.
 */
@Entity(
    tableName = "course_notes",
    foreignKeys = @ForeignKey(
            entity = Course.class,
            parentColumns = "id",
            childColumns = "course_id",
            onDelete = CASCADE
    ),
    indices = {@Index(value = {"course_id"})}
)
public class CourseNote {

    /**
     * The autogenerated primary key
     */
    @PrimaryKey(autoGenerate = true)
    private Long id;

    /**
     * The parent course ID
     */
    @ColumnInfo(name = "course_id")
    private Long courseId;

    /**
     * The course note
     */
    @ColumnInfo(name = "note")
    private String note;

    /**
     * The course note ID getter
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * The course note ID setter
     * @param id The autogenerated ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * The parent course ID getter
     * @return courseId
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * The parent course ID setter
     * @param courseId The parent course ID
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * The note getter
     * @return note
     */
    public String getNote() {
        return note;
    }

    /**
     * The note setter
     * @param note The course note
     */
    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public String toString() {
        return note;
    }
}
