package android.wgunn.collegeschedulelite.Entity;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.util.Date;

/**
 * The Term entity models a row in the terms table
 */
@Entity(
    tableName = "terms",
    indices = {@Index(value = {"name"}, unique = true)}
)
public class Term {

    /**
     * The autogenerated primary key
     */
    @PrimaryKey(autoGenerate = true)
    private Long id;

    /**
     * The term name
     */
    @NonNull
    @ColumnInfo(name = "name")
    private String name;

    /**
     * The term start date
     */
    @ColumnInfo(name = "start_date")
    private Date startDate;

    /**
     * The term end date
     */
    @ColumnInfo(name = "end_date")
    private Date endDate;

    /**
     * The public constructor
     *
     * @param name The term name
     * @param startDate The term start date
     * @param endDate The term end date
     */
    public Term(@NonNull String name, Date startDate, Date endDate) {
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    /**
     * The ID getter
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * The ID setter
     * @param id the term ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * The name getter
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * The name setter
     * @param name The term name
     */
    public void setName(@NonNull String name) {
        this.name = name;
    }

    /**
     * The start date getter
     * @return startDate
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * The start date setter
     * @param startDate The term start date
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * The end date getter
     * @return endDate
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * The end date setter
     * @param endDate The term end date
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @NonNull
    @Override
    public String toString() {
        return name;
    }
}
